 controller_list:
  - name: gazebo_ros_control
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
joint_state_controller:
	type: joint_state_controller/JointStateController
	publish_rate: 50
