gripper:                    #useful if you use a namespace for the robot
    # Publish -ns:joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    r_finger_effort:
        type: effort_controllers/JointEffortController
        joint: J1
        pid: {p: 1, d: 0.1, i: 0}
    l_finger_effort:
        type: effort_controllers/JointEffortController
        joint: J2
        pid: {p: 1, d: 0.1, i: 0}

    r_finger_position:
        type: effort_controllers/JointPositionController
        joint: J1
        pid: {p: 1, d: 0.1, i: 0}
    l_finger_position:
        type: effort_controllers/JointPositionController
        joint: J2
        pid: {p: 1, d: 0.1, i: 0}

#    panda_hand_controller:
#        type: effort_controllers/JointTrajectoryController
#        joints:
#            - panda_finger_joint1
#            - panda_finger_joint2
#
#        gains:
#            panda_finger_joint1: { p: 5, d: 3.0, i: 0, i_clamp: 1 }
#            panda_finger_joint2: { p: 5, d: 1.0, i: 0, i_clamp: 1 }
